version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_local
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: restaurantdb
      POSTGRES_USER: restaurantdb_owner
      POSTGRES_PASSWORD: npg_oJtgE9OUej3m
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
